buildscript {
    ext.kotlin_version = '1.9.24'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }

    // Universal namespace fix for all plugins
    subprojects {
        project.plugins.withId('com.android.library') {
            android {
                // Set namespace for known plugins
                if (project.name == 'flutter_keyboard_visibility') {
                    namespace "com.jrai.flutter_keyboard_visibility"
                } else if (project.name == 'record') {
                    namespace "com.llfbandit.record"
                }
                // Default namespace for other plugins
                else {
                    namespace = "com.example.${project.name}"
                }
                compileSdk 34
                ndkVersion "25.1.8937393"
            }
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}